### ISSUE TITLE
Space in project path not well handled

### ISSUE THREAD

**Issue by jairbubbles** [liamkf/msfastbuild#3]
My project is in folder:
`C:\Users\Julien\Source\Workspaces\Bitmap Font`

When buildding from solution explorer I get:

```
Building BitmapFont.vcxproj Release Win32
Launching FBuild with command line: -p BitmapFont.vcxproj -c Release -f Win32 -s C:\Users\Julien\Source\Workspaces\Bitmap Font\BitmapFont.sln -a"-dist -ide" -b "fbuild.exe"
Building BitmapFont
Failed to open BFF 'C:\Users\Julien\Source\Workspaces\Bitmap'
0/1 built.
```

Through build menu I just have:

```
Launching FBuild with command line: -s C:\Users\Julien\Source\Workspaces\Bitmap Font\BitmapFont.sln -c Release -f Win32 -a"-dist -ide" -b "fbuild.exe"
0/0 built.
```

**Comment by liamkf** [comment]
Yup that's not great! Should be fixed in the latest.

**Comment by jairbubbles** [comment]
Tested with version 0.18 (1.8 in extension manager) but I still have the same issue.

**Comment by liamkf** [comment]
Ah hmm, seems like I might have to dig into FBuild a bit, I'm passing a reasonable quoted string but it seems to not parse correctly when there are other arguments on the command line: i.e. 
`$>fbuild -config "C:/space bees/fbuild.bff"`
works but
`$>fbuild -dist -ide -config "C:/space bees/fbuild.bff"`
doesn't.

**Comment by liamkf** [comment]
Mmm hmm looks like we're not passing the quoted string through to the subprocess that gets created in fbuild when -ide is passed. I submitted a little fix for it in my fastbuild fork and will let FASTBuild know,  removing -ide in the vsix options should allow things to build in the meantime with the latest.

**Comment by jairbubbles** [comment]
Thx!
Do you think you can include your custom fbuild.exe in your releases? It would be easier for me to test.

**Comment by liamkf** [comment]
Hmm, I can post a version from our branch tonight, I think it may have features that are not necessarily wanted by the general public though! :)

**Comment by liamkf** [comment]
Ok give it a try when you have time and let me know!

**Comment by jairbubbles** [comment]
Well I have that now:
`1> Error: opening file 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\1033\clui.dll' in Compiler ToolManifest`

Reminds me something... :-S

**Comment by liamkf** [comment]
Hmmmm that's weird! Can you delete your bff and try again (annoying I know... maybe I'll add some versioning detection or something... :))? If it's not there I should definitely detect it...

**Comment by jairbubbles** [comment]
Yes that must be the reason. I'll check... as soon as I'm able to find a way to fix my corrupted visual studio installation. I've been trying to fix it the whole day, that's just fuc***\* crazy.

**Comment by jairbubbles** [comment]
Fixed (when using your fbuild.exe version) !
